### ISSUE TITLE
Fix scripts in branch remote

### ISSUE THREAD

**Issue by dvorapa** [dvorapa/pywikibot#1]
Issues:
- [x] mwparserfromhell/wikitextparser: 87, 88, 52, 53, 56, 57, 59, 89, 49, 51, 54, 55, 58, 48, 50
- [x] MemoryError: 87, 52
- [x] handlearg: 87, 52, 49, 51, 54, 55
- [x] mysql encoding: 53, 56, 57, 59, 89, 48
- [x] grepnot: 89

### mwparserfromhell/wikitextparser
```
WARNING: /mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py:2065: FutureWarning: 
Pywikibot needs a MediaWiki markup parser.
Please install the requested module with either

    pip install "mwparserfromhell>=0.5.0"

or

    pip install "wikitextparser>=0.47.0"

Using pywikibot without MediaWiki markup parser is deprecated for 15 days.
  self.text, True, True)
```

### MemoryError
- **87**: Nezvládá uložit nějakou špatnou stránku; souvisí s mwpfh/wtp
```
ERROR: MemoryError: 
Traceback (most recent call last):
  File "pwb.py", line 365, in <module>
    if not main():
  File "pwb.py", line 360, in main
    file_package)
  File "pwb.py", line 74, in run_python_file
    main_mod.__dict__)
  File "./scripts/userscripts/propagacni-reference.py", line 192, in <module>
    main()
  File "./scripts/userscripts/propagacni-reference.py", line 184, in main
    bot.run()  # guess what it does
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1525, in run
    self.treat(page)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1804, in treat
    self.treat_page()
  File "./scripts/userscripts/propagacni-reference.py", line 138, in treat_page
    self.put_current(text, summary=self.shrnuti)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1864, in put_current
    super().put_current(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1832, in put_current
    **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1323, in userPut
    page.text = newtext
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 584, in text
    self.botMayEdit()  # T262136, T267770
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 1036, in botMayEdit
    templates = self.templatesWithParams()
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 2089, in templatesWithParams
    templates = self.raw_extracted_templates
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 2065, in raw_extracted_templates
    self.text, True, True)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/textlib.py", line 1632, in extract_templates_and_params
    return _extract_templates_and_params_regex(text, False, strip)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/textlib.py", line 1846, in _extract_templates_and_params_regex
    links[int(m2.group(1))])
MemoryError
CRITICAL: Exiting due to uncaught exception <class 'MemoryError'>

@@ -46,2 +46,2 @@ ***
- | titul = Čeští reprezentanti deklasovali na ME v malé kopané Izrael a dále narazí na Bulhary {{!}} Aktuálně.cz ***
+ | titul = Čeští reprezentanti deklasovali na ME v malé kopané Izrael a dále narazí na Bulhary ***
- | periodikum = Aktuálně.cz - Víte, co se právě děje ***
+ | periodikum = Aktuálně.cz ***

Edit summary: Robot: -nevhodný text z automaticky vygenerované reference

0 pages read
0 pages written
0 pages skipped
Execution time: 1 seconds
Script terminated by exception:

ERROR: MemoryError: 
Traceback (most recent call last):
  File "pwb.py", line 365, in <module>
    if not main():
  File "pwb.py", line 360, in main
    file_package)
  File "pwb.py", line 74, in run_python_file
    main_mod.__dict__)
  File "./scripts/userscripts/propagacni-reference.py", line 192, in <module>
    main()
  File "./scripts/userscripts/propagacni-reference.py", line 184, in main
    bot.run()  # guess what it does
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1525, in run
    self.treat(page)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1804, in treat
    self.treat_page()
  File "./scripts/userscripts/propagacni-reference.py", line 138, in treat_page
    self.put_current(text, summary=self.shrnuti)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1864, in put_current
    super().put_current(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1832, in put_current
    **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1323, in userPut
    page.text = newtext
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 584, in text
    self.botMayEdit()  # T262136, T267770
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 1036, in botMayEdit
    templates = self.templatesWithParams()
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 2089, in templatesWithParams
    templates = self.raw_extracted_templates
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/page/__init__.py", line 2065, in raw_extracted_templates
    self.text, True, True)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/textlib.py", line 1632, in extract_templates_and_params
    return _extract_templates_and_params_regex(text, False, strip)
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/textlib.py", line 1856, in _extract_templates_and_params_regex
    param_val = param_val.strip()
MemoryError
CRITICAL: Exiting due to uncaught exception <class 'MemoryError'>
```
- **52**: Potřebuje zprofilovat
```
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 5.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 10.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 20.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 40.0 seconds before retrying.
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1502, in run
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/pagegenerators.py", line 2153, in PreloadingGenerator
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/site/_generators.py", line 167, in preloadpages
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 2724, in __iter__
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 2568, in __iter__
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1745, in submit
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1497, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1874, in wait
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1251, in sleep
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1264, in stopme
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pwb.py", line 365, in <module>
  File "pwb.py", line 360, in main
  File "pwb.py", line 74, in run_python_file
  File "./scripts/userscripts/neexistujici-kotvy.py", line 275, in <module>
  File "./scripts/userscripts/neexistujici-kotvy.py", line 261, in main
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1539, in run
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1407, in exit
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1264, in stopme
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError
CRITICAL: Exiting due to uncaught exception <class 'MemoryError'>
```

### handlearg
```
WARNING: ./scripts/userscripts/neexistujici-kotvy.py:240: FutureWarning: pywikibot.pagegenerators.GeneratorFactory.handleArg is deprecated for 3 months and 18 days; use handle_arg instead.
  if gen_factory.handleArg(arg):
```

### mysql encoding
```
WARNING: /mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/pagegenerators.py:2687: FutureWarning: encoding argument of pywikibot.data.mysql.mysql_query is deprecated.
  verbose=verbose)
```

**Comment by dvorapa** [comment]
52 moved to a specific issue #2
