### ISSUE TITLE
52: MemoryError

### ISSUE THREAD

**Issue by dvorapa** [dvorapa/pywikibot#2]
Potřebuje zprofilovat, např. pomocí https://pypi.org/project/memory-profiler/:
```
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 5.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 10.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 20.0 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1475, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 252, in request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/tools/__init__.py", line 1585, in wrapper
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 412, in fetch
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 479, in _decide_encoding
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/comms/http.py", line 455, in _try_decode
MemoryError

WARNING: Waiting 40.0 seconds before retrying.
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1502, in run
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/pagegenerators.py", line 2153, in PreloadingGenerator
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/site/_generators.py", line 167, in preloadpages
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 2724, in __iter__
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 2568, in __iter__
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1745, in submit
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1497, in _http_request
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/data/api.py", line 1874, in wait
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1251, in sleep
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1264, in stopme
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pwb.py", line 365, in <module>
  File "pwb.py", line 360, in main
  File "pwb.py", line 74, in run_python_file
  File "./scripts/userscripts/neexistujici-kotvy.py", line 275, in <module>
  File "./scripts/userscripts/neexistujici-kotvy.py", line 261, in main
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1539, in run
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/bot.py", line 1407, in exit
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1264, in stopme
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/__init__.py", line 1313, in _flush
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in drop
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 204, in <listcomp>
  File "/mnt/nfs/labstore-secondary-tools-project/dvorapabot/pywikibot/pywikibot/throttle.py", line 81, in _read_file
MemoryError
CRITICAL: Exiting due to uncaught exception <class 'MemoryError'>
```

**Comment by dvorapa** [comment]
as_link available_options

**Comment by dvorapa** [comment]
What a thrill!
